/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.EventSubscription;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventSubscriptionRecord extends UpdatableRecordImpl<EventSubscriptionRecord> implements Record4<Integer, String, String, Boolean> {

	private static final long serialVersionUID = -582596372;

	/**
	 * Setter for <code>public.event_subscription.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.event_subscription.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.event_subscription.recipient_email</code>.
	 */
	public void setRecipientEmail(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.event_subscription.recipient_email</code>.
	 */
	public String getRecipientEmail() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.event_subscription.sport_types</code>.
	 */
	public void setSportTypes(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.event_subscription.sport_types</code>.
	 */
	public String getSportTypes() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.event_subscription.active</code>.
	 */
	public void setActive(Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.event_subscription.active</code>.
	 */
	public Boolean getActive() {
		return (Boolean) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Boolean> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Boolean> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return EventSubscription.EVENT_SUBSCRIPTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return EventSubscription.EVENT_SUBSCRIPTION.RECIPIENT_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return EventSubscription.EVENT_SUBSCRIPTION.SPORT_TYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return EventSubscription.EVENT_SUBSCRIPTION.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getRecipientEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSportTypes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventSubscriptionRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventSubscriptionRecord value2(String value) {
		setRecipientEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventSubscriptionRecord value3(String value) {
		setSportTypes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventSubscriptionRecord value4(Boolean value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventSubscriptionRecord values(Integer value1, String value2, String value3, Boolean value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventSubscriptionRecord
	 */
	public EventSubscriptionRecord() {
		super(EventSubscription.EVENT_SUBSCRIPTION);
	}

	/**
	 * Create a detached, initialised EventSubscriptionRecord
	 */
	public EventSubscriptionRecord(Integer id, String recipientEmail, String sportTypes, Boolean active) {
		super(EventSubscription.EVENT_SUBSCRIPTION);

		setValue(0, id);
		setValue(1, recipientEmail);
		setValue(2, sportTypes);
		setValue(3, active);
	}
}
