/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.Initiate;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InitiateRecord extends UpdatableRecordImpl<InitiateRecord> implements Record12<Integer, Integer, Integer, String, Integer, Date, String, String, String, String, String, String> {

	private static final long serialVersionUID = 872175831;

	/**
	 * Setter for <code>public.initiate.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.initiate.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.initiate.sphere_id</code>.
	 */
	public void setSphereId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.initiate.sphere_id</code>.
	 */
	public Integer getSphereId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.initiate.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.initiate.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.initiate.description</code>.
	 */
	public void setDescription(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.initiate.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.initiate.group_id</code>.
	 */
	public void setGroupId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.initiate.group_id</code>.
	 */
	public Integer getGroupId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.initiate.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.initiate.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(5);
	}

	/**
	 * Setter for <code>public.initiate.client_uid</code>.
	 */
	public void setClientUid(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.initiate.client_uid</code>.
	 */
	public String getClientUid() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.initiate.ip_address</code>.
	 */
	public void setIpAddress(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.initiate.ip_address</code>.
	 */
	public String getIpAddress() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.initiate.name</code>.
	 */
	public void setName(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.initiate.name</code>.
	 */
	public String getName() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.initiate.necessity</code>.
	 */
	public void setNecessity(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.initiate.necessity</code>.
	 */
	public String getNecessity() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>public.initiate.advantages</code>.
	 */
	public void setAdvantages(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.initiate.advantages</code>.
	 */
	public String getAdvantages() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>public.initiate.other_sphere_name</code>.
	 */
	public void setOtherSphereName(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.initiate.other_sphere_name</code>.
	 */
	public String getOtherSphereName() {
		return (String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, Integer, Integer, String, Integer, Date, String, String, String, String, String, String> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, Integer, Integer, String, Integer, Date, String, String, String, String, String, String> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Initiate.INITIATE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Initiate.INITIATE.SPHERE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Initiate.INITIATE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Initiate.INITIATE.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Initiate.INITIATE.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field6() {
		return Initiate.INITIATE.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Initiate.INITIATE.CLIENT_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Initiate.INITIATE.IP_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Initiate.INITIATE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Initiate.INITIATE.NECESSITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Initiate.INITIATE.ADVANTAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Initiate.INITIATE.OTHER_SPHERE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSphereId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value6() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getClientUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getIpAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getNecessity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getAdvantages();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getOtherSphereName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value2(Integer value) {
		setSphereId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value3(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value5(Integer value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value6(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value7(String value) {
		setClientUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value8(String value) {
		setIpAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value9(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value10(String value) {
		setNecessity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value11(String value) {
		setAdvantages(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord value12(String value) {
		setOtherSphereName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InitiateRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Date value6, String value7, String value8, String value9, String value10, String value11, String value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InitiateRecord
	 */
	public InitiateRecord() {
		super(Initiate.INITIATE);
	}

	/**
	 * Create a detached, initialised InitiateRecord
	 */
	public InitiateRecord(Integer id, Integer sphereId, Integer userId, String description, Integer groupId, Date createDate, String clientUid, String ipAddress, String name, String necessity, String advantages, String otherSphereName) {
		super(Initiate.INITIATE);

		setValue(0, id);
		setValue(1, sphereId);
		setValue(2, userId);
		setValue(3, description);
		setValue(4, groupId);
		setValue(5, createDate);
		setValue(6, clientUid);
		setValue(7, ipAddress);
		setValue(8, name);
		setValue(9, necessity);
		setValue(10, advantages);
		setValue(11, otherSphereName);
	}
}
