/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.Organisation;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationRecord extends UpdatableRecordImpl<OrganisationRecord> implements Record10<Integer, String, String, Integer, String, String, Date, String, String, String> {

	private static final long serialVersionUID = 1226672318;

	/**
	 * Setter for <code>public.organisation.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.organisation.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.organisation.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.organisation.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.organisation.address</code>.
	 */
	public void setAddress(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.organisation.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.organisation.region_id</code>.
	 */
	public void setRegionId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.organisation.region_id</code>.
	 */
	public Integer getRegionId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.organisation.mobile_phone</code>.
	 */
	public void setMobilePhone(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.organisation.mobile_phone</code>.
	 */
	public String getMobilePhone() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.organisation.condition</code>.
	 */
	public void setCondition(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.organisation.condition</code>.
	 */
	public String getCondition() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.organisation.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.organisation.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>public.organisation.web</code>.
	 */
	public void setWeb(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.organisation.web</code>.
	 */
	public String getWeb() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.organisation.mail</code>.
	 */
	public void setMail(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.organisation.mail</code>.
	 */
	public String getMail() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.organisation.logo_url</code>.
	 */
	public void setLogoUrl(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.organisation.logo_url</code>.
	 */
	public String getLogoUrl() {
		return (String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, String, String, Integer, String, String, Date, String, String, String> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, String, String, Integer, String, String, Date, String, String, String> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Organisation.ORGANISATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Organisation.ORGANISATION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Organisation.ORGANISATION.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Organisation.ORGANISATION.REGION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Organisation.ORGANISATION.MOBILE_PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Organisation.ORGANISATION.CONDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return Organisation.ORGANISATION.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Organisation.ORGANISATION.WEB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Organisation.ORGANISATION.MAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Organisation.ORGANISATION.LOGO_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getRegionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMobilePhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCondition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getWeb();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getMail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getLogoUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value3(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value4(Integer value) {
		setRegionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value5(String value) {
		setMobilePhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value6(String value) {
		setCondition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value7(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value8(String value) {
		setWeb(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value9(String value) {
		setMail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord value10(String value) {
		setLogoUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganisationRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, Date value7, String value8, String value9, String value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OrganisationRecord
	 */
	public OrganisationRecord() {
		super(Organisation.ORGANISATION);
	}

	/**
	 * Create a detached, initialised OrganisationRecord
	 */
	public OrganisationRecord(Integer id, String name, String address, Integer regionId, String mobilePhone, String condition, Date createDate, String web, String mail, String logoUrl) {
		super(Organisation.ORGANISATION);

		setValue(0, id);
		setValue(1, name);
		setValue(2, address);
		setValue(3, regionId);
		setValue(4, mobilePhone);
		setValue(5, condition);
		setValue(6, createDate);
		setValue(7, web);
		setValue(8, mail);
		setValue(9, logoUrl);
	}
}
