/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.PriorityVote;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PriorityVoteRecord extends UpdatableRecordImpl<PriorityVoteRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Integer, Date> {

	private static final long serialVersionUID = 96945444;

	/**
	 * Setter for <code>public.priority_vote.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.priority_vote.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.priority_vote.priority_id</code>.
	 */
	public void setPriorityId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.priority_vote.priority_id</code>.
	 */
	public Integer getPriorityId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.priority_vote.priority_item_id</code>.
	 */
	public void setPriorityItemId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.priority_vote.priority_item_id</code>.
	 */
	public Integer getPriorityItemId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.priority_vote.answer_id</code>.
	 */
	public void setAnswerId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.priority_vote.answer_id</code>.
	 */
	public Integer getAnswerId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.priority_vote.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.priority_vote.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.priority_vote.group_id</code>.
	 */
	public void setGroupId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.priority_vote.group_id</code>.
	 */
	public Integer getGroupId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.priority_vote.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.priority_vote.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Date> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Date> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PriorityVote.PRIORITY_VOTE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return PriorityVote.PRIORITY_VOTE.PRIORITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return PriorityVote.PRIORITY_VOTE.PRIORITY_ITEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return PriorityVote.PRIORITY_VOTE.ANSWER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return PriorityVote.PRIORITY_VOTE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return PriorityVote.PRIORITY_VOTE.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return PriorityVote.PRIORITY_VOTE.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPriorityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getPriorityItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getAnswerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord value2(Integer value) {
		setPriorityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord value3(Integer value) {
		setPriorityItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord value4(Integer value) {
		setAnswerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord value5(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord value6(Integer value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord value7(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PriorityVoteRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Date value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PriorityVoteRecord
	 */
	public PriorityVoteRecord() {
		super(PriorityVote.PRIORITY_VOTE);
	}

	/**
	 * Create a detached, initialised PriorityVoteRecord
	 */
	public PriorityVoteRecord(Integer id, Integer priorityId, Integer priorityItemId, Integer answerId, Integer userId, Integer groupId, Date createDate) {
		super(PriorityVote.PRIORITY_VOTE);

		setValue(0, id);
		setValue(1, priorityId);
		setValue(2, priorityItemId);
		setValue(3, answerId);
		setValue(4, userId);
		setValue(5, groupId);
		setValue(6, createDate);
	}
}
