/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.Reform;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReformRecord extends UpdatableRecordImpl<ReformRecord> implements Record16<Integer, String, Integer, String, String, String, String, String, String, String, String, Date, Integer, String, String, Integer> {

	private static final long serialVersionUID = 1395424039;

	/**
	 * Setter for <code>public.reform.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.reform.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.reform.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.reform.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.reform.reform_type_id</code>.
	 */
	public void setReformTypeId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.reform.reform_type_id</code>.
	 */
	public Integer getReformTypeId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.reform.progress_bar_name_1</code>.
	 */
	public void setProgressBarName_1(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.reform.progress_bar_name_1</code>.
	 */
	public String getProgressBarName_1() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.reform.progress_bar_percent_1</code>.
	 */
	public void setProgressBarPercent_1(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.reform.progress_bar_percent_1</code>.
	 */
	public String getProgressBarPercent_1() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.reform.progress_bar_name_2</code>.
	 */
	public void setProgressBarName_2(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.reform.progress_bar_name_2</code>.
	 */
	public String getProgressBarName_2() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.reform.progress_bar_percent_2</code>.
	 */
	public void setProgressBarPercent_2(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.reform.progress_bar_percent_2</code>.
	 */
	public String getProgressBarPercent_2() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.reform.progress_bar_name_3</code>.
	 */
	public void setProgressBarName_3(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.reform.progress_bar_name_3</code>.
	 */
	public String getProgressBarName_3() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.reform.progress_bar_percent_3</code>.
	 */
	public void setProgressBarPercent_3(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.reform.progress_bar_percent_3</code>.
	 */
	public String getProgressBarPercent_3() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.reform.general_info</code>.
	 */
	public void setGeneralInfo(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.reform.general_info</code>.
	 */
	public String getGeneralInfo() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>public.reform.experience</code>.
	 */
	public void setExperience(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.reform.experience</code>.
	 */
	public String getExperience() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>public.reform.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.reform.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(11);
	}

	/**
	 * Setter for <code>public.reform.creator_id</code>.
	 */
	public void setCreatorId(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.reform.creator_id</code>.
	 */
	public Integer getCreatorId() {
		return (Integer) getValue(12);
	}

	/**
	 * Setter for <code>public.reform.note</code>.
	 */
	public void setNote(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>public.reform.note</code>.
	 */
	public String getNote() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>public.reform.image_name</code>.
	 */
	public void setImageName(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>public.reform.image_name</code>.
	 */
	public String getImageName() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>public.reform.status_id</code>.
	 */
	public void setStatusId(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>public.reform.status_id</code>.
	 */
	public Integer getStatusId() {
		return (Integer) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, String, Integer, String, String, String, String, String, String, String, String, Date, Integer, String, String, Integer> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, String, Integer, String, String, String, String, String, String, String, String, Date, Integer, String, String, Integer> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Reform.REFORM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Reform.REFORM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Reform.REFORM.REFORM_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Reform.REFORM.PROGRESS_BAR_NAME_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Reform.REFORM.PROGRESS_BAR_PERCENT_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Reform.REFORM.PROGRESS_BAR_NAME_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Reform.REFORM.PROGRESS_BAR_PERCENT_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Reform.REFORM.PROGRESS_BAR_NAME_3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Reform.REFORM.PROGRESS_BAR_PERCENT_3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Reform.REFORM.GENERAL_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Reform.REFORM.EXPERIENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field12() {
		return Reform.REFORM.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return Reform.REFORM.CREATOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return Reform.REFORM.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field15() {
		return Reform.REFORM.IMAGE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return Reform.REFORM.STATUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getReformTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getProgressBarName_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getProgressBarPercent_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getProgressBarName_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getProgressBarPercent_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getProgressBarName_3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getProgressBarPercent_3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getGeneralInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getExperience();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value12() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getCreatorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value15() {
		return getImageName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getStatusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value3(Integer value) {
		setReformTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value4(String value) {
		setProgressBarName_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value5(String value) {
		setProgressBarPercent_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value6(String value) {
		setProgressBarName_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value7(String value) {
		setProgressBarPercent_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value8(String value) {
		setProgressBarName_3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value9(String value) {
		setProgressBarPercent_3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value10(String value) {
		setGeneralInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value11(String value) {
		setExperience(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value12(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value13(Integer value) {
		setCreatorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value14(String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value15(String value) {
		setImageName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord value16(Integer value) {
		setStatusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Date value12, Integer value13, String value14, String value15, Integer value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReformRecord
	 */
	public ReformRecord() {
		super(Reform.REFORM);
	}

	/**
	 * Create a detached, initialised ReformRecord
	 */
	public ReformRecord(Integer id, String name, Integer reformTypeId, String progressBarName_1, String progressBarPercent_1, String progressBarName_2, String progressBarPercent_2, String progressBarName_3, String progressBarPercent_3, String generalInfo, String experience, Date createDate, Integer creatorId, String note, String imageName, Integer statusId) {
		super(Reform.REFORM);

		setValue(0, id);
		setValue(1, name);
		setValue(2, reformTypeId);
		setValue(3, progressBarName_1);
		setValue(4, progressBarPercent_1);
		setValue(5, progressBarName_2);
		setValue(6, progressBarPercent_2);
		setValue(7, progressBarName_3);
		setValue(8, progressBarPercent_3);
		setValue(9, generalInfo);
		setValue(10, experience);
		setValue(11, createDate);
		setValue(12, creatorId);
		setValue(13, note);
		setValue(14, imageName);
		setValue(15, statusId);
	}
}
