/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.SessionPoll;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionPollRecord extends UpdatableRecordImpl<SessionPollRecord> implements Record5<Integer, Integer, String, String, Integer> {

	private static final long serialVersionUID = 233543658;

	/**
	 * Setter for <code>public.session_poll.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.session_poll.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.session_poll.session_id</code>.
	 */
	public void setSessionId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.session_poll.session_id</code>.
	 */
	public Integer getSessionId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.session_poll.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.session_poll.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.session_poll.description</code>.
	 */
	public void setDescription(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.session_poll.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.session_poll.order_by_number</code>.
	 */
	public void setOrderByNumber(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.session_poll.order_by_number</code>.
	 */
	public Integer getOrderByNumber() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return SessionPoll.SESSION_POLL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return SessionPoll.SESSION_POLL.SESSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SessionPoll.SESSION_POLL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SessionPoll.SESSION_POLL.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return SessionPoll.SESSION_POLL.ORDER_BY_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSessionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getOrderByNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollRecord value2(Integer value) {
		setSessionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollRecord value5(Integer value) {
		setOrderByNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SessionPollRecord
	 */
	public SessionPollRecord() {
		super(SessionPoll.SESSION_POLL);
	}

	/**
	 * Create a detached, initialised SessionPollRecord
	 */
	public SessionPollRecord(Integer id, Integer sessionId, String name, String description, Integer orderByNumber) {
		super(SessionPoll.SESSION_POLL);

		setValue(0, id);
		setValue(1, sessionId);
		setValue(2, name);
		setValue(3, description);
		setValue(4, orderByNumber);
	}
}
