/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.SessionVote;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionVoteRecord extends UpdatableRecordImpl<SessionVoteRecord> implements Record9<Integer, Integer, Integer, String, Boolean, Integer, String, String, Date> {

	private static final long serialVersionUID = 1666241893;

	/**
	 * Setter for <code>public.session_vote.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.session_vote.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.session_vote.session_id</code>.
	 */
	public void setSessionId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.session_vote.session_id</code>.
	 */
	public Integer getSessionId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.session_vote.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.session_vote.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.session_vote.mail</code>.
	 */
	public void setMail(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.session_vote.mail</code>.
	 */
	public String getMail() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.session_vote.agreed</code>.
	 */
	public void setAgreed(Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.session_vote.agreed</code>.
	 */
	public Boolean getAgreed() {
		return (Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.session_vote.range_id</code>.
	 */
	public void setRangeId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.session_vote.range_id</code>.
	 */
	public Integer getRangeId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.session_vote.profession</code>.
	 */
	public void setProfession(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.session_vote.profession</code>.
	 */
	public String getProfession() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.session_vote.field_of_activity</code>.
	 */
	public void setFieldOfActivity(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.session_vote.field_of_activity</code>.
	 */
	public String getFieldOfActivity() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.session_vote.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.session_vote.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Integer, Integer, String, Boolean, Integer, String, String, Date> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Integer, Integer, String, Boolean, Integer, String, String, Date> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return SessionVote.SESSION_VOTE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return SessionVote.SESSION_VOTE.SESSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return SessionVote.SESSION_VOTE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SessionVote.SESSION_VOTE.MAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field5() {
		return SessionVote.SESSION_VOTE.AGREED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return SessionVote.SESSION_VOTE.RANGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return SessionVote.SESSION_VOTE.PROFESSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return SessionVote.SESSION_VOTE.FIELD_OF_ACTIVITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field9() {
		return SessionVote.SESSION_VOTE.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSessionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value5() {
		return getAgreed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getRangeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getProfession();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getFieldOfActivity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value9() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value2(Integer value) {
		setSessionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value3(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value4(String value) {
		setMail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value5(Boolean value) {
		setAgreed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value6(Integer value) {
		setRangeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value7(String value) {
		setProfession(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value8(String value) {
		setFieldOfActivity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord value9(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionVoteRecord values(Integer value1, Integer value2, Integer value3, String value4, Boolean value5, Integer value6, String value7, String value8, Date value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SessionVoteRecord
	 */
	public SessionVoteRecord() {
		super(SessionVote.SESSION_VOTE);
	}

	/**
	 * Create a detached, initialised SessionVoteRecord
	 */
	public SessionVoteRecord(Integer id, Integer sessionId, Integer userId, String mail, Boolean agreed, Integer rangeId, String profession, String fieldOfActivity, Date createDate) {
		super(SessionVote.SESSION_VOTE);

		setValue(0, id);
		setValue(1, sessionId);
		setValue(2, userId);
		setValue(3, mail);
		setValue(4, agreed);
		setValue(5, rangeId);
		setValue(6, profession);
		setValue(7, fieldOfActivity);
		setValue(8, createDate);
	}
}
