/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.SessionPollVote;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionPollVoteRecord extends UpdatableRecordImpl<SessionPollVoteRecord> implements Record11<Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, String, String, Date> {

	private static final long serialVersionUID = -456758812;

	/**
	 * Setter for <code>public.session_poll_vote.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.session_poll_vote.reform_id</code>.
	 */
	public void setReformId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.reform_id</code>.
	 */
	public Integer getReformId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.session_poll_vote.session_id</code>.
	 */
	public void setSessionId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.session_id</code>.
	 */
	public Integer getSessionId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.session_poll_vote.question_id</code>.
	 */
	public void setQuestionId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.question_id</code>.
	 */
	public Integer getQuestionId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.session_poll_vote.answer_id</code>.
	 */
	public void setAnswerId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.answer_id</code>.
	 */
	public Integer getAnswerId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.session_poll_vote.answer_note</code>.
	 */
	public void setAnswerNote(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.answer_note</code>.
	 */
	public String getAnswerNote() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.session_poll_vote.session_vote_id</code>.
	 */
	public void setSessionVoteId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.session_vote_id</code>.
	 */
	public Integer getSessionVoteId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.session_poll_vote.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.user_id</code>.
	 */
	public Integer getUserId() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.session_poll_vote.ip_address</code>.
	 */
	public void setIpAddress(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.ip_address</code>.
	 */
	public String getIpAddress() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.session_poll_vote.client_uid</code>.
	 */
	public void setClientUid(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.client_uid</code>.
	 */
	public String getClientUid() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>public.session_poll_vote.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.session_poll_vote.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, String, String, Date> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, String, String, Date> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return SessionPollVote.SESSION_POLL_VOTE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return SessionPollVote.SESSION_POLL_VOTE.REFORM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return SessionPollVote.SESSION_POLL_VOTE.SESSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return SessionPollVote.SESSION_POLL_VOTE.QUESTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return SessionPollVote.SESSION_POLL_VOTE.ANSWER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return SessionPollVote.SESSION_POLL_VOTE.ANSWER_NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return SessionPollVote.SESSION_POLL_VOTE.SESSION_VOTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return SessionPollVote.SESSION_POLL_VOTE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return SessionPollVote.SESSION_POLL_VOTE.IP_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return SessionPollVote.SESSION_POLL_VOTE.CLIENT_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field11() {
		return SessionPollVote.SESSION_POLL_VOTE.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getReformId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSessionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getQuestionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getAnswerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAnswerNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getSessionVoteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getIpAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getClientUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value11() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value2(Integer value) {
		setReformId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value3(Integer value) {
		setSessionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value4(Integer value) {
		setQuestionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value5(Integer value) {
		setAnswerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value6(String value) {
		setAnswerNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value7(Integer value) {
		setSessionVoteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value8(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value9(String value) {
		setIpAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value10(String value) {
		setClientUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord value11(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionPollVoteRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, Integer value7, Integer value8, String value9, String value10, Date value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SessionPollVoteRecord
	 */
	public SessionPollVoteRecord() {
		super(SessionPollVote.SESSION_POLL_VOTE);
	}

	/**
	 * Create a detached, initialised SessionPollVoteRecord
	 */
	public SessionPollVoteRecord(Integer id, Integer reformId, Integer sessionId, Integer questionId, Integer answerId, String answerNote, Integer sessionVoteId, Integer userId, String ipAddress, String clientUid, Date createDate) {
		super(SessionPollVote.SESSION_POLL_VOTE);

		setValue(0, id);
		setValue(1, reformId);
		setValue(2, sessionId);
		setValue(3, questionId);
		setValue(4, answerId);
		setValue(5, answerNote);
		setValue(6, sessionVoteId);
		setValue(7, userId);
		setValue(8, ipAddress);
		setValue(9, clientUid);
		setValue(10, createDate);
	}
}
