/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.Sportsman;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportsmanRecord extends UpdatableRecordImpl<SportsmanRecord> implements Record21<Integer, String, String, Date, Integer, Integer, Integer, Date, Integer, Integer, String, String, String, Boolean, Date, Date, Date, String, String, Boolean, Boolean> {

	private static final long serialVersionUID = -717019717;

	/**
	 * Setter for <code>public.sportsman.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.sportsman.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.sportsman.first_name</code>.
	 */
	public void setFirstName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.sportsman.first_name</code>.
	 */
	public String getFirstName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.sportsman.last_name</code>.
	 */
	public void setLastName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.sportsman.last_name</code>.
	 */
	public String getLastName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.sportsman.birth_date</code>.
	 */
	public void setBirthDate(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.sportsman.birth_date</code>.
	 */
	public Date getBirthDate() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>public.sportsman.region_id</code>.
	 */
	public void setRegionId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.sportsman.region_id</code>.
	 */
	public Integer getRegionId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.sportsman.sport_type_id</code>.
	 */
	public void setSportTypeId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.sportsman.sport_type_id</code>.
	 */
	public Integer getSportTypeId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.sportsman.gender_id</code>.
	 */
	public void setGenderId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.sportsman.gender_id</code>.
	 */
	public Integer getGenderId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.sportsman.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.sportsman.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(7);
	}

	/**
	 * Setter for <code>public.sportsman.rank_id</code>.
	 */
	public void setRankId(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.sportsman.rank_id</code>.
	 */
	public Integer getRankId() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>public.sportsman.city_id</code>.
	 */
	public void setCityId(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.sportsman.city_id</code>.
	 */
	public Integer getCityId() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>public.sportsman.height</code>.
	 */
	public void setHeight(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.sportsman.height</code>.
	 */
	public String getHeight() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>public.sportsman.biography</code>.
	 */
	public void setBiography(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.sportsman.biography</code>.
	 */
	public String getBiography() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>public.sportsman.image_url</code>.
	 */
	public void setImageUrl(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.sportsman.image_url</code>.
	 */
	public String getImageUrl() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>public.sportsman.is_para_sportsman</code>.
	 */
	public void setIsParaSportsman(Boolean value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>public.sportsman.is_para_sportsman</code>.
	 */
	public Boolean getIsParaSportsman() {
		return (Boolean) getValue(13);
	}

	/**
	 * Setter for <code>public.sportsman.death_date</code>.
	 */
	public void setDeathDate(Date value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>public.sportsman.death_date</code>.
	 */
	public Date getDeathDate() {
		return (Date) getValue(14);
	}

	/**
	 * Setter for <code>public.sportsman.career_start_date</code>.
	 */
	public void setCareerStartDate(Date value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>public.sportsman.career_start_date</code>.
	 */
	public Date getCareerStartDate() {
		return (Date) getValue(15);
	}

	/**
	 * Setter for <code>public.sportsman.career_end_date</code>.
	 */
	public void setCareerEndDate(Date value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>public.sportsman.career_end_date</code>.
	 */
	public Date getCareerEndDate() {
		return (Date) getValue(16);
	}

	/**
	 * Setter for <code>public.sportsman.district</code>.
	 */
	public void setDistrict(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>public.sportsman.district</code>.
	 */
	public String getDistrict() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>public.sportsman.comment</code>.
	 */
	public void setComment(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>public.sportsman.comment</code>.
	 */
	public String getComment() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>public.sportsman.is_olimpic</code>.
	 */
	public void setIsOlimpic(Boolean value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>public.sportsman.is_olimpic</code>.
	 */
	public Boolean getIsOlimpic() {
		return (Boolean) getValue(19);
	}

	/**
	 * Setter for <code>public.sportsman.is_paralympic</code>.
	 */
	public void setIsParalympic(Boolean value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>public.sportsman.is_paralympic</code>.
	 */
	public Boolean getIsParalympic() {
		return (Boolean) getValue(20);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record21 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row21<Integer, String, String, Date, Integer, Integer, Integer, Date, Integer, Integer, String, String, String, Boolean, Date, Date, Date, String, String, Boolean, Boolean> fieldsRow() {
		return (Row21) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row21<Integer, String, String, Date, Integer, Integer, Integer, Date, Integer, Integer, String, String, String, Boolean, Date, Date, Date, String, String, Boolean, Boolean> valuesRow() {
		return (Row21) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Sportsman.SPORTSMAN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Sportsman.SPORTSMAN.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Sportsman.SPORTSMAN.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return Sportsman.SPORTSMAN.BIRTH_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Sportsman.SPORTSMAN.REGION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Sportsman.SPORTSMAN.SPORT_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Sportsman.SPORTSMAN.GENDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field8() {
		return Sportsman.SPORTSMAN.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Sportsman.SPORTSMAN.RANK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Sportsman.SPORTSMAN.CITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Sportsman.SPORTSMAN.HEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Sportsman.SPORTSMAN.BIOGRAPHY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return Sportsman.SPORTSMAN.IMAGE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field14() {
		return Sportsman.SPORTSMAN.IS_PARA_SPORTSMAN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field15() {
		return Sportsman.SPORTSMAN.DEATH_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field16() {
		return Sportsman.SPORTSMAN.CAREER_START_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field17() {
		return Sportsman.SPORTSMAN.CAREER_END_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field18() {
		return Sportsman.SPORTSMAN.DISTRICT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field19() {
		return Sportsman.SPORTSMAN.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field20() {
		return Sportsman.SPORTSMAN.IS_OLIMPIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field21() {
		return Sportsman.SPORTSMAN.IS_PARALYMPIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getBirthDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getRegionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getSportTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getGenderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value8() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getRankId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getCityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getHeight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getBiography();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getImageUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value14() {
		return getIsParaSportsman();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value15() {
		return getDeathDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value16() {
		return getCareerStartDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value17() {
		return getCareerEndDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value18() {
		return getDistrict();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value19() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value20() {
		return getIsOlimpic();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value21() {
		return getIsParalympic();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value2(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value3(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value4(Date value) {
		setBirthDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value5(Integer value) {
		setRegionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value6(Integer value) {
		setSportTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value7(Integer value) {
		setGenderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value8(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value9(Integer value) {
		setRankId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value10(Integer value) {
		setCityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value11(String value) {
		setHeight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value12(String value) {
		setBiography(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value13(String value) {
		setImageUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value14(Boolean value) {
		setIsParaSportsman(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value15(Date value) {
		setDeathDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value16(Date value) {
		setCareerStartDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value17(Date value) {
		setCareerEndDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value18(String value) {
		setDistrict(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value19(String value) {
		setComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value20(Boolean value) {
		setIsOlimpic(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord value21(Boolean value) {
		setIsParalympic(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRecord values(Integer value1, String value2, String value3, Date value4, Integer value5, Integer value6, Integer value7, Date value8, Integer value9, Integer value10, String value11, String value12, String value13, Boolean value14, Date value15, Date value16, Date value17, String value18, String value19, Boolean value20, Boolean value21) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		value20(value20);
		value21(value21);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SportsmanRecord
	 */
	public SportsmanRecord() {
		super(Sportsman.SPORTSMAN);
	}

	/**
	 * Create a detached, initialised SportsmanRecord
	 */
	public SportsmanRecord(Integer id, String firstName, String lastName, Date birthDate, Integer regionId, Integer sportTypeId, Integer genderId, Date createDate, Integer rankId, Integer cityId, String height, String biography, String imageUrl, Boolean isParaSportsman, Date deathDate, Date careerStartDate, Date careerEndDate, String district, String comment, Boolean isOlimpic, Boolean isParalympic) {
		super(Sportsman.SPORTSMAN);

		setValue(0, id);
		setValue(1, firstName);
		setValue(2, lastName);
		setValue(3, birthDate);
		setValue(4, regionId);
		setValue(5, sportTypeId);
		setValue(6, genderId);
		setValue(7, createDate);
		setValue(8, rankId);
		setValue(9, cityId);
		setValue(10, height);
		setValue(11, biography);
		setValue(12, imageUrl);
		setValue(13, isParaSportsman);
		setValue(14, deathDate);
		setValue(15, careerStartDate);
		setValue(16, careerEndDate);
		setValue(17, district);
		setValue(18, comment);
		setValue(19, isOlimpic);
		setValue(20, isParalympic);
	}
}
