/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.SportsmanFile;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportsmanFileRecord extends UpdatableRecordImpl<SportsmanFileRecord> implements Record7<Integer, String, Date, Integer, String, Integer, Boolean> {

	private static final long serialVersionUID = 1500712591;

	/**
	 * Setter for <code>public.sportsman_file.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.sportsman_file.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.sportsman_file.file_name</code>.
	 */
	public void setFileName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.sportsman_file.file_name</code>.
	 */
	public String getFileName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.sportsman_file.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.sportsman_file.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>public.sportsman_file.sportsman_id</code>.
	 */
	public void setSportsmanId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.sportsman_file.sportsman_id</code>.
	 */
	public Integer getSportsmanId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.sportsman_file.file_url</code>.
	 */
	public void setFileUrl(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.sportsman_file.file_url</code>.
	 */
	public String getFileUrl() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.sportsman_file.file_type_id</code>.
	 */
	public void setFileTypeId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.sportsman_file.file_type_id</code>.
	 */
	public Integer getFileTypeId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.sportsman_file.is_main</code>.
	 */
	public void setIsMain(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.sportsman_file.is_main</code>.
	 */
	public Boolean getIsMain() {
		return (Boolean) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, Date, Integer, String, Integer, Boolean> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, Date, Integer, String, Integer, Boolean> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return SportsmanFile.SPORTSMAN_FILE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SportsmanFile.SPORTSMAN_FILE.FILE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return SportsmanFile.SPORTSMAN_FILE.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return SportsmanFile.SPORTSMAN_FILE.SPORTSMAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return SportsmanFile.SPORTSMAN_FILE.FILE_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return SportsmanFile.SPORTSMAN_FILE.FILE_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return SportsmanFile.SPORTSMAN_FILE.IS_MAIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFileName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getSportsmanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getFileUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getFileTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getIsMain();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord value2(String value) {
		setFileName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord value3(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord value4(Integer value) {
		setSportsmanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord value5(String value) {
		setFileUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord value6(Integer value) {
		setFileTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord value7(Boolean value) {
		setIsMain(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanFileRecord values(Integer value1, String value2, Date value3, Integer value4, String value5, Integer value6, Boolean value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SportsmanFileRecord
	 */
	public SportsmanFileRecord() {
		super(SportsmanFile.SPORTSMAN_FILE);
	}

	/**
	 * Create a detached, initialised SportsmanFileRecord
	 */
	public SportsmanFileRecord(Integer id, String fileName, Date createDate, Integer sportsmanId, String fileUrl, Integer fileTypeId, Boolean isMain) {
		super(SportsmanFile.SPORTSMAN_FILE);

		setValue(0, id);
		setValue(1, fileName);
		setValue(2, createDate);
		setValue(3, sportsmanId);
		setValue(4, fileUrl);
		setValue(5, fileTypeId);
		setValue(6, isMain);
	}
}
