/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.SystemProperties;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemPropertiesRecord extends UpdatableRecordImpl<SystemPropertiesRecord> implements Record6<Integer, String, String, String, Integer, Date> {

	private static final long serialVersionUID = -1026089251;

	/**
	 * Setter for <code>public.system_properties.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.system_properties.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.system_properties.description</code>.
	 */
	public void setDescription(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.system_properties.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.system_properties.key</code>.
	 */
	public void setKey(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.system_properties.key</code>.
	 */
	public String getKey() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.system_properties.value</code>.
	 */
	public void setValue(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.system_properties.value</code>.
	 */
	public String getValue() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.system_properties.group_id</code>.
	 */
	public void setGroupId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.system_properties.group_id</code>.
	 */
	public Integer getGroupId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.system_properties.last_modification_date</code>.
	 */
	public void setLastModificationDate(Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.system_properties.last_modification_date</code>.
	 */
	public Date getLastModificationDate() {
		return (Date) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, Integer, Date> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, Integer, Date> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return SystemProperties.SYSTEM_PROPERTIES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SystemProperties.SYSTEM_PROPERTIES.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SystemProperties.SYSTEM_PROPERTIES.KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SystemProperties.SYSTEM_PROPERTIES.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return SystemProperties.SYSTEM_PROPERTIES.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field6() {
		return SystemProperties.SYSTEM_PROPERTIES.LAST_MODIFICATION_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value6() {
		return getLastModificationDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemPropertiesRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemPropertiesRecord value2(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemPropertiesRecord value3(String value) {
		setKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemPropertiesRecord value4(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemPropertiesRecord value5(Integer value) {
		setGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemPropertiesRecord value6(Date value) {
		setLastModificationDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemPropertiesRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Date value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SystemPropertiesRecord
	 */
	public SystemPropertiesRecord() {
		super(SystemProperties.SYSTEM_PROPERTIES);
	}

	/**
	 * Create a detached, initialised SystemPropertiesRecord
	 */
	public SystemPropertiesRecord(Integer id, String description, String key, String value, Integer groupId, Date lastModificationDate) {
		super(SystemProperties.SYSTEM_PROPERTIES);

		setValue(0, id);
		setValue(1, description);
		setValue(2, key);
		setValue(3, value);
		setValue(4, groupId);
		setValue(5, lastModificationDate);
	}
}
