/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables.records;


import ge.economy.involve.database.database.tables.Users;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record15<String, String, String, String, String, String, Integer, Integer, String, Boolean, Integer, Date, Integer, Integer, Integer> {

	private static final long serialVersionUID = -971903057;

	/**
	 * Setter for <code>public.users.first_name</code>.
	 */
	public void setFirstName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.users.first_name</code>.
	 */
	public String getFirstName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.users.last_name</code>.
	 */
	public void setLastName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.users.last_name</code>.
	 */
	public String getLastName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.users.org_name</code>.
	 */
	public void setOrgName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.users.org_name</code>.
	 */
	public String getOrgName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.users.id_number</code>.
	 */
	public void setIdNumber(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.users.id_number</code>.
	 */
	public String getIdNumber() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.users.phone</code>.
	 */
	public void setPhone(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.users.phone</code>.
	 */
	public String getPhone() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.users.email</code>.
	 */
	public void setEmail(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.users.email</code>.
	 */
	public String getEmail() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.users.gender_id</code>.
	 */
	public void setGenderId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.users.gender_id</code>.
	 */
	public Integer getGenderId() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.users.user_type_id</code>.
	 */
	public void setUserTypeId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.users.user_type_id</code>.
	 */
	public Integer getUserTypeId() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.users.password</code>.
	 */
	public void setPassword(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.users.password</code>.
	 */
	public String getPassword() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.users.is_approved</code>.
	 */
	public void setIsApproved(Boolean value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.users.is_approved</code>.
	 */
	public Boolean getIsApproved() {
		return (Boolean) getValue(9);
	}

	/**
	 * Setter for <code>public.users.creator_id</code>.
	 */
	public void setCreatorId(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.users.creator_id</code>.
	 */
	public Integer getCreatorId() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>public.users.create_date</code>.
	 */
	public void setCreateDate(Date value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.users.create_date</code>.
	 */
	public Date getCreateDate() {
		return (Date) getValue(11);
	}

	/**
	 * Setter for <code>public.users.user_group_id</code>.
	 */
	public void setUserGroupId(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.users.user_group_id</code>.
	 */
	public Integer getUserGroupId() {
		return (Integer) getValue(12);
	}

	/**
	 * Setter for <code>public.users.status_id</code>.
	 */
	public void setStatusId(Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>public.users.status_id</code>.
	 */
	public Integer getStatusId() {
		return (Integer) getValue(13);
	}

	/**
	 * Setter for <code>public.users.id</code>.
	 */
	public void setId(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>public.users.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<String, String, String, String, String, String, Integer, Integer, String, Boolean, Integer, Date, Integer, Integer, Integer> fieldsRow() {
		return (Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<String, String, String, String, String, String, Integer, Integer, String, Boolean, Integer, Date, Integer, Integer, Integer> valuesRow() {
		return (Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Users.USERS.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Users.USERS.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Users.USERS.ORG_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Users.USERS.ID_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Users.USERS.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Users.USERS.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Users.USERS.GENDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Users.USERS.USER_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Users.USERS.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field10() {
		return Users.USERS.IS_APPROVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return Users.USERS.CREATOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field12() {
		return Users.USERS.CREATE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return Users.USERS.USER_GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field14() {
		return Users.USERS.STATUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return Users.USERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getOrgName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getIdNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getGenderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getUserTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value10() {
		return getIsApproved();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getCreatorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value12() {
		return getCreateDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getUserGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value14() {
		return getStatusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value1(String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value2(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value3(String value) {
		setOrgName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value4(String value) {
		setIdNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value5(String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value6(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value7(Integer value) {
		setGenderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value8(Integer value) {
		setUserTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value9(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value10(Boolean value) {
		setIsApproved(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value11(Integer value) {
		setCreatorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value12(Date value) {
		setCreateDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value13(Integer value) {
		setUserGroupId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value14(Integer value) {
		setStatusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value15(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Integer value8, String value9, Boolean value10, Integer value11, Date value12, Integer value13, Integer value14, Integer value15) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(String firstName, String lastName, String orgName, String idNumber, String phone, String email, Integer genderId, Integer userTypeId, String password, Boolean isApproved, Integer creatorId, Date createDate, Integer userGroupId, Integer statusId, Integer id) {
		super(Users.USERS);

		setValue(0, firstName);
		setValue(1, lastName);
		setValue(2, orgName);
		setValue(3, idNumber);
		setValue(4, phone);
		setValue(5, email);
		setValue(6, genderId);
		setValue(7, userTypeId);
		setValue(8, password);
		setValue(9, isApproved);
		setValue(10, creatorId);
		setValue(11, createDate);
		setValue(12, userGroupId);
		setValue(13, statusId);
		setValue(14, id);
	}
}
