/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database;


import ge.economy.involve.database.database.routines.UpdateModifiedColumn;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>public.update_modified_column</code>
	 */
	public static Object updateModifiedColumn(Configuration configuration) {
		UpdateModifiedColumn f = new UpdateModifiedColumn();

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.update_modified_column</code> as a field.
	 */
	public static Field<Object> updateModifiedColumn() {
		UpdateModifiedColumn f = new UpdateModifiedColumn();

		return f.asField();
	}
}
