/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.Trainer_id_seq</code>
	 */
	public static final Sequence<Long> TRAINER_ID_SEQ = new SequenceImpl<Long>("Trainer_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.award_id_seq</code>
	 */
	public static final Sequence<Long> AWARD_ID_SEQ = new SequenceImpl<Long>("award_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.category_id_seq</code>
	 */
	public static final Sequence<Long> CATEGORY_ID_SEQ = new SequenceImpl<Long>("category_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.championship_id_seq</code>
	 */
	public static final Sequence<Long> CHAMPIONSHIP_ID_SEQ = new SequenceImpl<Long>("championship_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.championship_sub_type_id_seq</code>
	 */
	public static final Sequence<Long> CHAMPIONSHIP_SUB_TYPE_ID_SEQ = new SequenceImpl<Long>("championship_sub_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.championship_type_relation_id_seq</code>
	 */
	public static final Sequence<Long> CHAMPIONSHIP_TYPE_RELATION_ID_SEQ = new SequenceImpl<Long>("championship_type_relation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.chempionship_type_id_seq</code>
	 */
	public static final Sequence<Long> CHEMPIONSHIP_TYPE_ID_SEQ = new SequenceImpl<Long>("chempionship_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.city_id_seq</code>
	 */
	public static final Sequence<Long> CITY_ID_SEQ = new SequenceImpl<Long>("city_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.condition_id_seq</code>
	 */
	public static final Sequence<Long> CONDITION_ID_SEQ = new SequenceImpl<Long>("condition_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.event_id_seq</code>
	 */
	public static final Sequence<Long> EVENT_ID_SEQ = new SequenceImpl<Long>("event_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.event_subscription_id_seq</code>
	 */
	public static final Sequence<Long> EVENT_SUBSCRIPTION_ID_SEQ = new SequenceImpl<Long>("event_subscription_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.event_type_id_seq</code>
	 */
	public static final Sequence<Long> EVENT_TYPE_ID_SEQ = new SequenceImpl<Long>("event_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.file_type_id_seq</code>
	 */
	public static final Sequence<Long> FILE_TYPE_ID_SEQ = new SequenceImpl<Long>("file_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.gender_id_seq</code>
	 */
	public static final Sequence<Long> GENDER_ID_SEQ = new SequenceImpl<Long>("gender_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.news_file_id_seq</code>
	 */
	public static final Sequence<Long> NEWS_FILE_ID_SEQ = new SequenceImpl<Long>("news_file_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.news_id_seq</code>
	 */
	public static final Sequence<Long> NEWS_ID_SEQ = new SequenceImpl<Long>("news_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.object_type_id_seq</code>
	 */
	public static final Sequence<Long> OBJECT_TYPE_ID_SEQ = new SequenceImpl<Long>("object_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.organisation_id_seq</code>
	 */
	public static final Sequence<Long> ORGANISATION_ID_SEQ = new SequenceImpl<Long>("organisation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.ownership_id_seq</code>
	 */
	public static final Sequence<Long> OWNERSHIP_ID_SEQ = new SequenceImpl<Long>("ownership_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.purpose_id_seq</code>
	 */
	public static final Sequence<Long> PURPOSE_ID_SEQ = new SequenceImpl<Long>("purpose_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.qualification_id_seq</code>
	 */
	public static final Sequence<Long> QUALIFICATION_ID_SEQ = new SequenceImpl<Long>("qualification_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.referee_id_seq</code>
	 */
	public static final Sequence<Long> REFEREE_ID_SEQ = new SequenceImpl<Long>("referee_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.referee_sport_type_id_seq</code>
	 */
	public static final Sequence<Long> REFEREE_SPORT_TYPE_ID_SEQ = new SequenceImpl<Long>("referee_sport_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.region_id_seq</code>
	 */
	public static final Sequence<Long> REGION_ID_SEQ = new SequenceImpl<Long>("region_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.result_id_seq</code>
	 */
	public static final Sequence<Long> RESULT_ID_SEQ = new SequenceImpl<Long>("result_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.section_id_seq</code>
	 */
	public static final Sequence<Long> SECTION_ID_SEQ = new SequenceImpl<Long>("section_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.sport_object_id_seq</code>
	 */
	public static final Sequence<Long> SPORT_OBJECT_ID_SEQ = new SequenceImpl<Long>("sport_object_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.sport_type_file_id_seq</code>
	 */
	public static final Sequence<Long> SPORT_TYPE_FILE_ID_SEQ = new SequenceImpl<Long>("sport_type_file_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.sport_type_id_seq</code>
	 */
	public static final Sequence<Long> SPORT_TYPE_ID_SEQ = new SequenceImpl<Long>("sport_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.sportsman_file_id_seq</code>
	 */
	public static final Sequence<Long> SPORTSMAN_FILE_ID_SEQ = new SequenceImpl<Long>("sportsman_file_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.sportsman_id_seq</code>
	 */
	public static final Sequence<Long> SPORTSMAN_ID_SEQ = new SequenceImpl<Long>("sportsman_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.sportsman_sport_type_id_seq</code>
	 */
	public static final Sequence<Long> SPORTSMAN_SPORT_TYPE_ID_SEQ = new SequenceImpl<Long>("sportsman_sport_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.sportsman_trainer_id_seq</code>
	 */
	public static final Sequence<Long> SPORTSMAN_TRAINER_ID_SEQ = new SequenceImpl<Long>("sportsman_trainer_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.statistic_category_id_seq</code>
	 */
	public static final Sequence<Long> STATISTIC_CATEGORY_ID_SEQ = new SequenceImpl<Long>("statistic_category_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.statistic_range_type_id_seq</code>
	 */
	public static final Sequence<Long> STATISTIC_RANGE_TYPE_ID_SEQ = new SequenceImpl<Long>("statistic_range_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.statistic_sport_type_id_seq</code>
	 */
	public static final Sequence<Long> STATISTIC_SPORT_TYPE_ID_SEQ = new SequenceImpl<Long>("statistic_sport_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.statistic_sportsman_id_seq</code>
	 */
	public static final Sequence<Long> STATISTIC_SPORTSMAN_ID_SEQ = new SequenceImpl<Long>("statistic_sportsman_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.statistic_type_id_seq</code>
	 */
	public static final Sequence<Long> STATISTIC_TYPE_ID_SEQ = new SequenceImpl<Long>("statistic_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.system_properties_group_id_seq</code>
	 */
	public static final Sequence<Long> SYSTEM_PROPERTIES_GROUP_ID_SEQ = new SequenceImpl<Long>("system_properties_group_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.system_properties_id_seq</code>
	 */
	public static final Sequence<Long> SYSTEM_PROPERTIES_ID_SEQ = new SequenceImpl<Long>("system_properties_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.title_id_seq</code>
	 */
	public static final Sequence<Long> TITLE_ID_SEQ = new SequenceImpl<Long>("title_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.trainer_sport_type_id_seq</code>
	 */
	public static final Sequence<Long> TRAINER_SPORT_TYPE_ID_SEQ = new SequenceImpl<Long>("trainer_sport_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.user_id_seq</code>
	 */
	public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.user_status_id_seq</code>
	 */
	public static final Sequence<Long> USER_STATUS_ID_SEQ = new SequenceImpl<Long>("user_status_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
