/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.AgeRangeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgeRange extends TableImpl<AgeRangeRecord> {

	private static final long serialVersionUID = 89215109;

	/**
	 * The reference instance of <code>public.age_range</code>
	 */
	public static final AgeRange AGE_RANGE = new AgeRange();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AgeRangeRecord> getRecordType() {
		return AgeRangeRecord.class;
	}

	/**
	 * The column <code>public.age_range.id</code>.
	 */
	public final TableField<AgeRangeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.age_range.name</code>.
	 */
	public final TableField<AgeRangeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.age_range.from</code>.
	 */
	public final TableField<AgeRangeRecord, Integer> FROM = createField("from", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.age_range.to</code>.
	 */
	public final TableField<AgeRangeRecord, Integer> TO = createField("to", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.age_range</code> table reference
	 */
	public AgeRange() {
		this("age_range", null);
	}

	/**
	 * Create an aliased <code>public.age_range</code> table reference
	 */
	public AgeRange(String alias) {
		this(alias, AGE_RANGE);
	}

	private AgeRange(String alias, Table<AgeRangeRecord> aliased) {
		this(alias, aliased, null);
	}

	private AgeRange(String alias, Table<AgeRangeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AgeRangeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_AGE_RANGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AgeRangeRecord> getPrimaryKey() {
		return Keys.AGE_RANGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AgeRangeRecord>> getKeys() {
		return Arrays.<UniqueKey<AgeRangeRecord>>asList(Keys.AGE_RANGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AgeRange as(String alias) {
		return new AgeRange(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AgeRange rename(String name) {
		return new AgeRange(name, null);
	}
}
