/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.tables.records.AwardRecord;
import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Award extends TableImpl<AwardRecord> {

	private static final long serialVersionUID = 353269371;

	/**
	 * The reference instance of <code>public.award</code>
	 */
	public static final Award AWARD = new Award();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AwardRecord> getRecordType() {
		return AwardRecord.class;
	}

	/**
	 * The column <code>public.award.id</code>.
	 */
	public final TableField<AwardRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.award.name</code>.
	 */
	public final TableField<AwardRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.award</code> table reference
	 */
	public Award() {
		this("award", null);
	}

	/**
	 * Create an aliased <code>public.award</code> table reference
	 */
	public Award(String alias) {
		this(alias, AWARD);
	}

	private Award(String alias, Table<AwardRecord> aliased) {
		this(alias, aliased, null);
	}

	private Award(String alias, Table<AwardRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AwardRecord, Integer> getIdentity() {
		return Keys.IDENTITY_AWARD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AwardRecord> getPrimaryKey() {
		return Keys.AWARD_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AwardRecord>> getKeys() {
		return Arrays.<UniqueKey<AwardRecord>>asList(Keys.AWARD_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Award as(String alias) {
		return new Award(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Award rename(String name) {
		return new Award(name, null);
	}
}
