/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.CityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City extends TableImpl<CityRecord> {

	private static final long serialVersionUID = -1847060264;

	/**
	 * The reference instance of <code>public.city</code>
	 */
	public static final City CITY = new City();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CityRecord> getRecordType() {
		return CityRecord.class;
	}

	/**
	 * The column <code>public.city.id</code>.
	 */
	public final TableField<CityRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.city.region_id</code>.
	 */
	public final TableField<CityRecord, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.city.name</code>.
	 */
	public final TableField<CityRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.city</code> table reference
	 */
	public City() {
		this("city", null);
	}

	/**
	 * Create an aliased <code>public.city</code> table reference
	 */
	public City(String alias) {
		this(alias, CITY);
	}

	private City(String alias, Table<CityRecord> aliased) {
		this(alias, aliased, null);
	}

	private City(String alias, Table<CityRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<CityRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CityRecord> getPrimaryKey() {
		return Keys.CITY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CityRecord>> getKeys() {
		return Arrays.<UniqueKey<CityRecord>>asList(Keys.CITY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public City as(String alias) {
		return new City(alias, this);
	}

	/**
	 * Rename this table
	 */
	public City rename(String name) {
		return new City(name, null);
	}
}
