/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.ConditionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Condition extends TableImpl<ConditionRecord> {

	private static final long serialVersionUID = 2004329327;

	/**
	 * The reference instance of <code>public.condition</code>
	 */
	public static final Condition CONDITION = new Condition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ConditionRecord> getRecordType() {
		return ConditionRecord.class;
	}

	/**
	 * The column <code>public.condition.id</code>.
	 */
	public final TableField<ConditionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.condition.name</code>.
	 */
	public final TableField<ConditionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.condition</code> table reference
	 */
	public Condition() {
		this("condition", null);
	}

	/**
	 * Create an aliased <code>public.condition</code> table reference
	 */
	public Condition(String alias) {
		this(alias, CONDITION);
	}

	private Condition(String alias, Table<ConditionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Condition(String alias, Table<ConditionRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ConditionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_CONDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ConditionRecord> getPrimaryKey() {
		return Keys.CONDITION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ConditionRecord>> getKeys() {
		return Arrays.<UniqueKey<ConditionRecord>>asList(Keys.CONDITION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Condition as(String alias) {
		return new Condition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Condition rename(String name) {
		return new Condition(name, null);
	}
}
