/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.EducationLevelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EducationLevel extends TableImpl<EducationLevelRecord> {

	private static final long serialVersionUID = -161842928;

	/**
	 * The reference instance of <code>public.education_level</code>
	 */
	public static final EducationLevel EDUCATION_LEVEL = new EducationLevel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EducationLevelRecord> getRecordType() {
		return EducationLevelRecord.class;
	}

	/**
	 * The column <code>public.education_level.id</code>.
	 */
	public final TableField<EducationLevelRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.education_level.name</code>.
	 */
	public final TableField<EducationLevelRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.education_level</code> table reference
	 */
	public EducationLevel() {
		this("education_level", null);
	}

	/**
	 * Create an aliased <code>public.education_level</code> table reference
	 */
	public EducationLevel(String alias) {
		this(alias, EDUCATION_LEVEL);
	}

	private EducationLevel(String alias, Table<EducationLevelRecord> aliased) {
		this(alias, aliased, null);
	}

	private EducationLevel(String alias, Table<EducationLevelRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EducationLevelRecord, Integer> getIdentity() {
		return Keys.IDENTITY_EDUCATION_LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EducationLevelRecord> getPrimaryKey() {
		return Keys.EDUCATION_LEVEL_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EducationLevelRecord>> getKeys() {
		return Arrays.<UniqueKey<EducationLevelRecord>>asList(Keys.EDUCATION_LEVEL_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EducationLevel as(String alias) {
		return new EducationLevel(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EducationLevel rename(String name) {
		return new EducationLevel(name, null);
	}
}
