/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.converter.TimestampConverter;
import ge.economy.involve.database.database.tables.records.NewsFileRecord;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsFile extends TableImpl<NewsFileRecord> {

	private static final long serialVersionUID = 222630148;

	/**
	 * The reference instance of <code>public.news_file</code>
	 */
	public static final NewsFile NEWS_FILE = new NewsFile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NewsFileRecord> getRecordType() {
		return NewsFileRecord.class;
	}

	/**
	 * The column <code>public.news_file.id</code>.
	 */
	public final TableField<NewsFileRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.news_file.news_id</code>.
	 */
	public final TableField<NewsFileRecord, Integer> NEWS_ID = createField("news_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.news_file.file_name</code>.
	 */
	public final TableField<NewsFileRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.news_file.is_main</code>.
	 */
	public final TableField<NewsFileRecord, Boolean> IS_MAIN = createField("is_main", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.news_file.create_date</code>.
	 */
	public final TableField<NewsFileRecord, Date> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new TimestampConverter());

	/**
	 * The column <code>public.news_file.file_url</code>.
	 */
	public final TableField<NewsFileRecord, String> FILE_URL = createField("file_url", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.news_file.file_type_id</code>.
	 */
	public final TableField<NewsFileRecord, Integer> FILE_TYPE_ID = createField("file_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.news_file</code> table reference
	 */
	public NewsFile() {
		this("news_file", null);
	}

	/**
	 * Create an aliased <code>public.news_file</code> table reference
	 */
	public NewsFile(String alias) {
		this(alias, NEWS_FILE);
	}

	private NewsFile(String alias, Table<NewsFileRecord> aliased) {
		this(alias, aliased, null);
	}

	private NewsFile(String alias, Table<NewsFileRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<NewsFileRecord, Integer> getIdentity() {
		return Keys.IDENTITY_NEWS_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NewsFileRecord> getPrimaryKey() {
		return Keys.NEWS_FILE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NewsFileRecord>> getKeys() {
		return Arrays.<UniqueKey<NewsFileRecord>>asList(Keys.NEWS_FILE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NewsFile as(String alias) {
		return new NewsFile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public NewsFile rename(String name) {
		return new NewsFile(name, null);
	}
}
