/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.ObjectTypeRecord;
import ge.economy.involve.database.database.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjectType extends TableImpl<ObjectTypeRecord> {

	private static final long serialVersionUID = 913483278;

	/**
	 * The reference instance of <code>public.object_type</code>
	 */
	public static final ObjectType OBJECT_TYPE = new ObjectType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ObjectTypeRecord> getRecordType() {
		return ObjectTypeRecord.class;
	}

	/**
	 * The column <code>public.object_type.id</code>.
	 */
	public final TableField<ObjectTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.object_type.name</code>.
	 */
	public final TableField<ObjectTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.object_type</code> table reference
	 */
	public ObjectType() {
		this("object_type", null);
	}

	/**
	 * Create an aliased <code>public.object_type</code> table reference
	 */
	public ObjectType(String alias) {
		this(alias, OBJECT_TYPE);
	}

	private ObjectType(String alias, Table<ObjectTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private ObjectType(String alias, Table<ObjectTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ObjectTypeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_OBJECT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ObjectTypeRecord> getPrimaryKey() {
		return Keys.OBJECT_TYPE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ObjectTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<ObjectTypeRecord>>asList(Keys.OBJECT_TYPE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ObjectType as(String alias) {
		return new ObjectType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ObjectType rename(String name) {
		return new ObjectType(name, null);
	}
}
