/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.PollAnswerRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollAnswer extends TableImpl<PollAnswerRecord> {

	private static final long serialVersionUID = 828873314;

	/**
	 * The reference instance of <code>public.poll_answer</code>
	 */
	public static final PollAnswer POLL_ANSWER = new PollAnswer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PollAnswerRecord> getRecordType() {
		return PollAnswerRecord.class;
	}

	/**
	 * The column <code>public.poll_answer.id</code>.
	 */
	public final TableField<PollAnswerRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.poll_answer.poll_id</code>.
	 */
	public final TableField<PollAnswerRecord, Integer> POLL_ID = createField("poll_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.poll_answer.value</code>.
	 */
	public final TableField<PollAnswerRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.poll_answer</code> table reference
	 */
	public PollAnswer() {
		this("poll_answer", null);
	}

	/**
	 * Create an aliased <code>public.poll_answer</code> table reference
	 */
	public PollAnswer(String alias) {
		this(alias, POLL_ANSWER);
	}

	private PollAnswer(String alias, Table<PollAnswerRecord> aliased) {
		this(alias, aliased, null);
	}

	private PollAnswer(String alias, Table<PollAnswerRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PollAnswerRecord> getPrimaryKey() {
		return Keys.POLL_ANSWER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PollAnswerRecord>> getKeys() {
		return Arrays.<UniqueKey<PollAnswerRecord>>asList(Keys.POLL_ANSWER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PollAnswer as(String alias) {
		return new PollAnswer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PollAnswer rename(String name) {
		return new PollAnswer(name, null);
	}
}
