/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.tables.records.PurposeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Purpose extends TableImpl<PurposeRecord> {

	private static final long serialVersionUID = 360573441;

	/**
	 * The reference instance of <code>public.purpose</code>
	 */
	public static final Purpose PURPOSE = new Purpose();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PurposeRecord> getRecordType() {
		return PurposeRecord.class;
	}

	/**
	 * The column <code>public.purpose.id</code>.
	 */
	public final TableField<PurposeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.purpose.name</code>.
	 */
	public final TableField<PurposeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.purpose</code> table reference
	 */
	public Purpose() {
		this("purpose", null);
	}

	/**
	 * Create an aliased <code>public.purpose</code> table reference
	 */
	public Purpose(String alias) {
		this(alias, PURPOSE);
	}

	private Purpose(String alias, Table<PurposeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Purpose(String alias, Table<PurposeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PurposeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PURPOSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PurposeRecord> getPrimaryKey() {
		return Keys.PURPOSE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PurposeRecord>> getKeys() {
		return Arrays.<UniqueKey<PurposeRecord>>asList(Keys.PURPOSE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Purpose as(String alias) {
		return new Purpose(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Purpose rename(String name) {
		return new Purpose(name, null);
	}
}
