/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.RefereeSportTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereeSportType extends TableImpl<RefereeSportTypeRecord> {

	private static final long serialVersionUID = 1544219419;

	/**
	 * The reference instance of <code>public.referee_sport_type</code>
	 */
	public static final RefereeSportType REFEREE_SPORT_TYPE = new RefereeSportType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RefereeSportTypeRecord> getRecordType() {
		return RefereeSportTypeRecord.class;
	}

	/**
	 * The column <code>public.referee_sport_type.id</code>.
	 */
	public final TableField<RefereeSportTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.referee_sport_type.referee_id</code>.
	 */
	public final TableField<RefereeSportTypeRecord, Integer> REFEREE_ID = createField("referee_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.referee_sport_type.sport_type_id</code>.
	 */
	public final TableField<RefereeSportTypeRecord, Integer> SPORT_TYPE_ID = createField("sport_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.referee_sport_type</code> table reference
	 */
	public RefereeSportType() {
		this("referee_sport_type", null);
	}

	/**
	 * Create an aliased <code>public.referee_sport_type</code> table reference
	 */
	public RefereeSportType(String alias) {
		this(alias, REFEREE_SPORT_TYPE);
	}

	private RefereeSportType(String alias, Table<RefereeSportTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private RefereeSportType(String alias, Table<RefereeSportTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RefereeSportTypeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_REFEREE_SPORT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RefereeSportTypeRecord> getPrimaryKey() {
		return Keys.REFEREE_SPORT_TYPE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RefereeSportTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<RefereeSportTypeRecord>>asList(Keys.REFEREE_SPORT_TYPE_PKEY, Keys.REFEREE_SPORT_TYPE_REFEREE_ID_SPORT_TYPE_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RefereeSportType as(String alias) {
		return new RefereeSportType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RefereeSportType rename(String name) {
		return new RefereeSportType(name, null);
	}
}
