/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.ReformTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReformType extends TableImpl<ReformTypeRecord> {

	private static final long serialVersionUID = 182221147;

	/**
	 * The reference instance of <code>public.reform_type</code>
	 */
	public static final ReformType REFORM_TYPE = new ReformType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReformTypeRecord> getRecordType() {
		return ReformTypeRecord.class;
	}

	/**
	 * The column <code>public.reform_type.id</code>.
	 */
	public final TableField<ReformTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.reform_type.name</code>.
	 */
	public final TableField<ReformTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.reform_type</code> table reference
	 */
	public ReformType() {
		this("reform_type", null);
	}

	/**
	 * Create an aliased <code>public.reform_type</code> table reference
	 */
	public ReformType(String alias) {
		this(alias, REFORM_TYPE);
	}

	private ReformType(String alias, Table<ReformTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReformType(String alias, Table<ReformTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ReformTypeRecord> getPrimaryKey() {
		return Keys.REFORM_TYPE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ReformTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<ReformTypeRecord>>asList(Keys.REFORM_TYPE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformType as(String alias) {
		return new ReformType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ReformType rename(String name) {
		return new ReformType(name, null);
	}
}
