/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.converter.TimestampConverter;
import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.ReformVoteRecord;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReformVote extends TableImpl<ReformVoteRecord> {

	private static final long serialVersionUID = 553235428;

	/**
	 * The reference instance of <code>public.reform_vote</code>
	 */
	public static final ReformVote REFORM_VOTE = new ReformVote();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReformVoteRecord> getRecordType() {
		return ReformVoteRecord.class;
	}

	/**
	 * The column <code>public.reform_vote.id</code>.
	 */
	public final TableField<ReformVoteRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.reform_vote.reform_id</code>.
	 */
	public final TableField<ReformVoteRecord, Integer> REFORM_ID = createField("reform_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.reform_vote.user_id</code>.
	 */
	public final TableField<ReformVoteRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.reform_vote.mail</code>.
	 */
	public final TableField<ReformVoteRecord, String> MAIL = createField("mail", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.reform_vote.agreed</code>.
	 */
	public final TableField<ReformVoteRecord, Boolean> AGREED = createField("agreed", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.reform_vote.range_id</code>.
	 */
	public final TableField<ReformVoteRecord, Integer> RANGE_ID = createField("range_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.reform_vote.profession</code>.
	 */
	public final TableField<ReformVoteRecord, String> PROFESSION = createField("profession", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.reform_vote.field_of_activity</code>.
	 */
	public final TableField<ReformVoteRecord, String> FIELD_OF_ACTIVITY = createField("field_of_activity", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.reform_vote.create_date</code>.
	 */
	public final TableField<ReformVoteRecord, Date> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new TimestampConverter());

	/**
	 * The column <code>public.reform_vote.client_guid</code>.
	 */
	public final TableField<ReformVoteRecord, String> CLIENT_GUID = createField("client_guid", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.reform_vote</code> table reference
	 */
	public ReformVote() {
		this("reform_vote", null);
	}

	/**
	 * Create an aliased <code>public.reform_vote</code> table reference
	 */
	public ReformVote(String alias) {
		this(alias, REFORM_VOTE);
	}

	private ReformVote(String alias, Table<ReformVoteRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReformVote(String alias, Table<ReformVoteRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ReformVoteRecord, Integer> getIdentity() {
		return Keys.IDENTITY_REFORM_VOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ReformVoteRecord> getPrimaryKey() {
		return Keys.SESSION_VOTE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ReformVoteRecord>> getKeys() {
		return Arrays.<UniqueKey<ReformVoteRecord>>asList(Keys.SESSION_VOTE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReformVote as(String alias) {
		return new ReformVote(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ReformVote rename(String name) {
		return new ReformVote(name, null);
	}
}
