/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.RegionRecord;
import ge.economy.involve.database.database.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Region extends TableImpl<RegionRecord> {

	private static final long serialVersionUID = 1100235043;

	/**
	 * The reference instance of <code>public.region</code>
	 */
	public static final Region REGION = new Region();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RegionRecord> getRecordType() {
		return RegionRecord.class;
	}

	/**
	 * The column <code>public.region.id</code>.
	 */
	public final TableField<RegionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.region.name</code>.
	 */
	public final TableField<RegionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.region</code> table reference
	 */
	public Region() {
		this("region", null);
	}

	/**
	 * Create an aliased <code>public.region</code> table reference
	 */
	public Region(String alias) {
		this(alias, REGION);
	}

	private Region(String alias, Table<RegionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Region(String alias, Table<RegionRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RegionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_REGION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RegionRecord> getPrimaryKey() {
		return Keys.REGION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RegionRecord>> getKeys() {
		return Arrays.<UniqueKey<RegionRecord>>asList(Keys.REGION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Region as(String alias) {
		return new Region(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Region rename(String name) {
		return new Region(name, null);
	}
}
