/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.converter.TimestampConverter;
import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.SessionFileRecord;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionFile extends TableImpl<SessionFileRecord> {

	private static final long serialVersionUID = 212490307;

	/**
	 * The reference instance of <code>public.session_file</code>
	 */
	public static final SessionFile SESSION_FILE = new SessionFile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SessionFileRecord> getRecordType() {
		return SessionFileRecord.class;
	}

	/**
	 * The column <code>public.session_file.id</code>.
	 */
	public final TableField<SessionFileRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.session_file.session_id</code>.
	 */
	public final TableField<SessionFileRecord, Integer> SESSION_ID = createField("session_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.session_file.file_type_id</code>.
	 */
	public final TableField<SessionFileRecord, Integer> FILE_TYPE_ID = createField("file_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.session_file.file_name</code>.
	 */
	public final TableField<SessionFileRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.session_file.create_date</code>.
	 */
	public final TableField<SessionFileRecord, Date> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new TimestampConverter());

	/**
	 * The column <code>public.session_file.name</code>.
	 */
	public final TableField<SessionFileRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.session_file</code> table reference
	 */
	public SessionFile() {
		this("session_file", null);
	}

	/**
	 * Create an aliased <code>public.session_file</code> table reference
	 */
	public SessionFile(String alias) {
		this(alias, SESSION_FILE);
	}

	private SessionFile(String alias, Table<SessionFileRecord> aliased) {
		this(alias, aliased, null);
	}

	private SessionFile(String alias, Table<SessionFileRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SessionFileRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SESSION_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SessionFileRecord> getPrimaryKey() {
		return Keys.SESSION_FILE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SessionFileRecord>> getKeys() {
		return Arrays.<UniqueKey<SessionFileRecord>>asList(Keys.SESSION_FILE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionFile as(String alias) {
		return new SessionFile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SessionFile rename(String name) {
		return new SessionFile(name, null);
	}
}
