/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.SportsmanRankRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportsmanRank extends TableImpl<SportsmanRankRecord> {

	private static final long serialVersionUID = -850670710;

	/**
	 * The reference instance of <code>public.sportsman_rank</code>
	 */
	public static final SportsmanRank SPORTSMAN_RANK = new SportsmanRank();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SportsmanRankRecord> getRecordType() {
		return SportsmanRankRecord.class;
	}

	/**
	 * The column <code>public.sportsman_rank.id</code>.
	 */
	public final TableField<SportsmanRankRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.sportsman_rank.name</code>.
	 */
	public final TableField<SportsmanRankRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.sportsman_rank</code> table reference
	 */
	public SportsmanRank() {
		this("sportsman_rank", null);
	}

	/**
	 * Create an aliased <code>public.sportsman_rank</code> table reference
	 */
	public SportsmanRank(String alias) {
		this(alias, SPORTSMAN_RANK);
	}

	private SportsmanRank(String alias, Table<SportsmanRankRecord> aliased) {
		this(alias, aliased, null);
	}

	private SportsmanRank(String alias, Table<SportsmanRankRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SportsmanRankRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SPORTSMAN_RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SportsmanRankRecord> getPrimaryKey() {
		return Keys.TITLE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SportsmanRankRecord>> getKeys() {
		return Arrays.<UniqueKey<SportsmanRankRecord>>asList(Keys.TITLE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanRank as(String alias) {
		return new SportsmanRank(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SportsmanRank rename(String name) {
		return new SportsmanRank(name, null);
	}
}
