/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.SportsmanTrainerRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportsmanTrainer extends TableImpl<SportsmanTrainerRecord> {

	private static final long serialVersionUID = -1205977653;

	/**
	 * The reference instance of <code>public.sportsman_trainer</code>
	 */
	public static final SportsmanTrainer SPORTSMAN_TRAINER = new SportsmanTrainer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SportsmanTrainerRecord> getRecordType() {
		return SportsmanTrainerRecord.class;
	}

	/**
	 * The column <code>public.sportsman_trainer.id</code>.
	 */
	public final TableField<SportsmanTrainerRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.sportsman_trainer.sportsman_id</code>.
	 */
	public final TableField<SportsmanTrainerRecord, Integer> SPORTSMAN_ID = createField("sportsman_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.sportsman_trainer.trainer_id</code>.
	 */
	public final TableField<SportsmanTrainerRecord, Integer> TRAINER_ID = createField("trainer_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.sportsman_trainer</code> table reference
	 */
	public SportsmanTrainer() {
		this("sportsman_trainer", null);
	}

	/**
	 * Create an aliased <code>public.sportsman_trainer</code> table reference
	 */
	public SportsmanTrainer(String alias) {
		this(alias, SPORTSMAN_TRAINER);
	}

	private SportsmanTrainer(String alias, Table<SportsmanTrainerRecord> aliased) {
		this(alias, aliased, null);
	}

	private SportsmanTrainer(String alias, Table<SportsmanTrainerRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SportsmanTrainerRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SPORTSMAN_TRAINER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SportsmanTrainerRecord> getPrimaryKey() {
		return Keys.SPORTSMAN_TRAINER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SportsmanTrainerRecord>> getKeys() {
		return Arrays.<UniqueKey<SportsmanTrainerRecord>>asList(Keys.SPORTSMAN_TRAINER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportsmanTrainer as(String alias) {
		return new SportsmanTrainer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SportsmanTrainer rename(String name) {
		return new SportsmanTrainer(name, null);
	}
}
