/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.SportObjectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportObject extends TableImpl<SportObjectRecord> {

	private static final long serialVersionUID = -890321794;

	/**
	 * The reference instance of <code>public.sport_object</code>
	 */
	public static final SportObject SPORT_OBJECT = new SportObject();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SportObjectRecord> getRecordType() {
		return SportObjectRecord.class;
	}

	/**
	 * The column <code>public.sport_object.id</code>.
	 */
	public final TableField<SportObjectRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.sport_object.name</code>.
	 */
	public final TableField<SportObjectRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.sport_object.object_type_id</code>.
	 */
	public final TableField<SportObjectRecord, Integer> OBJECT_TYPE_ID = createField("object_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.sport_object.address</code>.
	 */
	public final TableField<SportObjectRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.sport_object.mobile_number</code>.
	 */
	public final TableField<SportObjectRecord, String> MOBILE_NUMBER = createField("mobile_number", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.sport_object</code> table reference
	 */
	public SportObject() {
		this("sport_object", null);
	}

	/**
	 * Create an aliased <code>public.sport_object</code> table reference
	 */
	public SportObject(String alias) {
		this(alias, SPORT_OBJECT);
	}

	private SportObject(String alias, Table<SportObjectRecord> aliased) {
		this(alias, aliased, null);
	}

	private SportObject(String alias, Table<SportObjectRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SportObjectRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SPORT_OBJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SportObjectRecord> getPrimaryKey() {
		return Keys.SPORT_OBJECT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SportObjectRecord>> getKeys() {
		return Arrays.<UniqueKey<SportObjectRecord>>asList(Keys.SPORT_OBJECT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportObject as(String alias) {
		return new SportObject(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SportObject rename(String name) {
		return new SportObject(name, null);
	}
}
