/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.SportTypeFileRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportTypeFile extends TableImpl<SportTypeFileRecord> {

	private static final long serialVersionUID = -1295261466;

	/**
	 * The reference instance of <code>public.sport_type_file</code>
	 */
	public static final SportTypeFile SPORT_TYPE_FILE = new SportTypeFile();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SportTypeFileRecord> getRecordType() {
		return SportTypeFileRecord.class;
	}

	/**
	 * The column <code>public.sport_type_file.id</code>.
	 */
	public final TableField<SportTypeFileRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.sport_type_file.file_name</code>.
	 */
	public final TableField<SportTypeFileRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.sport_type_file.sport_type_id</code>.
	 */
	public final TableField<SportTypeFileRecord, Integer> SPORT_TYPE_ID = createField("sport_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.sport_type_file.file_type_id</code>.
	 */
	public final TableField<SportTypeFileRecord, Integer> FILE_TYPE_ID = createField("file_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.sport_type_file</code> table reference
	 */
	public SportTypeFile() {
		this("sport_type_file", null);
	}

	/**
	 * Create an aliased <code>public.sport_type_file</code> table reference
	 */
	public SportTypeFile(String alias) {
		this(alias, SPORT_TYPE_FILE);
	}

	private SportTypeFile(String alias, Table<SportTypeFileRecord> aliased) {
		this(alias, aliased, null);
	}

	private SportTypeFile(String alias, Table<SportTypeFileRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SportTypeFileRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SPORT_TYPE_FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SportTypeFileRecord> getPrimaryKey() {
		return Keys.SPORT_TYPE_FILE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SportTypeFileRecord>> getKeys() {
		return Arrays.<UniqueKey<SportTypeFileRecord>>asList(Keys.SPORT_TYPE_FILE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportTypeFile as(String alias) {
		return new SportTypeFile(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SportTypeFile rename(String name) {
		return new SportTypeFile(name, null);
	}
}
