/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.StatisticSportTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatisticSportType extends TableImpl<StatisticSportTypeRecord> {

	private static final long serialVersionUID = -851369840;

	/**
	 * The reference instance of <code>public.statistic_sport_type</code>
	 */
	public static final StatisticSportType STATISTIC_SPORT_TYPE = new StatisticSportType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StatisticSportTypeRecord> getRecordType() {
		return StatisticSportTypeRecord.class;
	}

	/**
	 * The column <code>public.statistic_sport_type.id</code>.
	 */
	public final TableField<StatisticSportTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.statistic_sport_type.statistic_id</code>.
	 */
	public final TableField<StatisticSportTypeRecord, Integer> STATISTIC_ID = createField("statistic_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.statistic_sport_type.sport_type_id</code>.
	 */
	public final TableField<StatisticSportTypeRecord, Integer> SPORT_TYPE_ID = createField("sport_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.statistic_sport_type</code> table reference
	 */
	public StatisticSportType() {
		this("statistic_sport_type", null);
	}

	/**
	 * Create an aliased <code>public.statistic_sport_type</code> table reference
	 */
	public StatisticSportType(String alias) {
		this(alias, STATISTIC_SPORT_TYPE);
	}

	private StatisticSportType(String alias, Table<StatisticSportTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private StatisticSportType(String alias, Table<StatisticSportTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<StatisticSportTypeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_STATISTIC_SPORT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StatisticSportTypeRecord> getPrimaryKey() {
		return Keys.STATISTIC_SPORT_TYPE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StatisticSportTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<StatisticSportTypeRecord>>asList(Keys.STATISTIC_SPORT_TYPE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatisticSportType as(String alias) {
		return new StatisticSportType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StatisticSportType rename(String name) {
		return new StatisticSportType(name, null);
	}
}
