/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.tables.records.StatisticTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatisticType extends TableImpl<StatisticTypeRecord> {

	private static final long serialVersionUID = -1558864968;

	/**
	 * The reference instance of <code>public.statistic_type</code>
	 */
	public static final StatisticType STATISTIC_TYPE = new StatisticType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StatisticTypeRecord> getRecordType() {
		return StatisticTypeRecord.class;
	}

	/**
	 * The column <code>public.statistic_type.id</code>.
	 */
	public final TableField<StatisticTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.statistic_type.name</code>.
	 */
	public final TableField<StatisticTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.statistic_type</code> table reference
	 */
	public StatisticType() {
		this("statistic_type", null);
	}

	/**
	 * Create an aliased <code>public.statistic_type</code> table reference
	 */
	public StatisticType(String alias) {
		this(alias, STATISTIC_TYPE);
	}

	private StatisticType(String alias, Table<StatisticTypeRecord> aliased) {
		this(alias, aliased, null);
	}

	private StatisticType(String alias, Table<StatisticTypeRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<StatisticTypeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_STATISTIC_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StatisticTypeRecord> getPrimaryKey() {
		return Keys.STATISTIC_TYPE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StatisticTypeRecord>> getKeys() {
		return Arrays.<UniqueKey<StatisticTypeRecord>>asList(Keys.STATISTIC_TYPE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatisticType as(String alias) {
		return new StatisticType(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StatisticType rename(String name) {
		return new StatisticType(name, null);
	}
}
