/**
 * This class is generated by jOOQ
 */
package ge.economy.involve.database.database.tables;


import ge.economy.involve.database.converter.TimestampConverter;
import ge.economy.involve.database.database.Keys;
import ge.economy.involve.database.database.Public;
import ge.economy.involve.database.database.tables.records.SystemPropertiesRecord;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemProperties extends TableImpl<SystemPropertiesRecord> {

	private static final long serialVersionUID = -1079691581;

	/**
	 * The reference instance of <code>public.system_properties</code>
	 */
	public static final SystemProperties SYSTEM_PROPERTIES = new SystemProperties();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SystemPropertiesRecord> getRecordType() {
		return SystemPropertiesRecord.class;
	}

	/**
	 * The column <code>public.system_properties.id</code>.
	 */
	public final TableField<SystemPropertiesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.system_properties.description</code>.
	 */
	public final TableField<SystemPropertiesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.system_properties.key</code>.
	 */
	public final TableField<SystemPropertiesRecord, String> KEY = createField("key", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.system_properties.value</code>.
	 */
	public final TableField<SystemPropertiesRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.system_properties.group_id</code>.
	 */
	public final TableField<SystemPropertiesRecord, Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.system_properties.last_modification_date</code>.
	 */
	public final TableField<SystemPropertiesRecord, Date> LAST_MODIFICATION_DATE = createField("last_modification_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new TimestampConverter());

	/**
	 * Create a <code>public.system_properties</code> table reference
	 */
	public SystemProperties() {
		this("system_properties", null);
	}

	/**
	 * Create an aliased <code>public.system_properties</code> table reference
	 */
	public SystemProperties(String alias) {
		this(alias, SYSTEM_PROPERTIES);
	}

	private SystemProperties(String alias, Table<SystemPropertiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private SystemProperties(String alias, Table<SystemPropertiesRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SystemPropertiesRecord, Integer> getIdentity() {
		return Keys.IDENTITY_SYSTEM_PROPERTIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SystemPropertiesRecord> getPrimaryKey() {
		return Keys.SYSTEM_PROPERTIES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SystemPropertiesRecord>> getKeys() {
		return Arrays.<UniqueKey<SystemPropertiesRecord>>asList(Keys.SYSTEM_PROPERTIES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<SystemPropertiesRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<SystemPropertiesRecord, ?>>asList(Keys.SYSTEM_PROPERTIES__SYSTEM_PROPERTIES_GROUP_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SystemProperties as(String alias) {
		return new SystemProperties(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SystemProperties rename(String name) {
		return new SystemProperties(name, null);
	}
}
